#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SScheduler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db143275")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertklasa(klasa instance);
    partial void Updateklasa(klasa instance);
    partial void Deleteklasa(klasa instance);
    partial void Insertnauczyciel(nauczyciel instance);
    partial void Updatenauczyciel(nauczyciel instance);
    partial void Deletenauczyciel(nauczyciel instance);
    partial void Insertprzedmiot(przedmiot instance);
    partial void Updateprzedmiot(przedmiot instance);
    partial void Deleteprzedmiot(przedmiot instance);
    partial void Insertsala(sala instance);
    partial void Updatesala(sala instance);
    partial void Deletesala(sala instance);
    partial void Insertnauczyciel_przedmiot(nauczyciel_przedmiot instance);
    partial void Updatenauczyciel_przedmiot(nauczyciel_przedmiot instance);
    partial void Deletenauczyciel_przedmiot(nauczyciel_przedmiot instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::SScheduler.Properties.Settings.Default.db143275ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<klasa> klasas
		{
			get
			{
				return this.GetTable<klasa>();
			}
		}
		
		public System.Data.Linq.Table<nauczyciel> nauczyciels
		{
			get
			{
				return this.GetTable<nauczyciel>();
			}
		}
		
		public System.Data.Linq.Table<przedmiot> przedmiots
		{
			get
			{
				return this.GetTable<przedmiot>();
			}
		}
		
		public System.Data.Linq.Table<sala> salas
		{
			get
			{
				return this.GetTable<sala>();
			}
		}
		
		public System.Data.Linq.Table<nauczyciel_przedmiot> nauczyciel_przedmiots
		{
			get
			{
				return this.GetTable<nauczyciel_przedmiot>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.klasa")]
	public partial class klasa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_klasa;
		
		private short _liczebnosc;
		
		private byte _rok;
		
		private char _identyfikator;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klasaChanging(System.Guid value);
    partial void Onid_klasaChanged();
    partial void OnliczebnoscChanging(short value);
    partial void OnliczebnoscChanged();
    partial void OnrokChanging(byte value);
    partial void OnrokChanged();
    partial void OnidentyfikatorChanging(char value);
    partial void OnidentyfikatorChanged();
    #endregion
		
		public klasa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klasa", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_klasa
		{
			get
			{
				return this._id_klasa;
			}
			set
			{
				if ((this._id_klasa != value))
				{
					this.Onid_klasaChanging(value);
					this.SendPropertyChanging();
					this._id_klasa = value;
					this.SendPropertyChanged("id_klasa");
					this.Onid_klasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liczebnosc", DbType="SmallInt NOT NULL")]
		public short liczebnosc
		{
			get
			{
				return this._liczebnosc;
			}
			set
			{
				if ((this._liczebnosc != value))
				{
					this.OnliczebnoscChanging(value);
					this.SendPropertyChanging();
					this._liczebnosc = value;
					this.SendPropertyChanged("liczebnosc");
					this.OnliczebnoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rok", DbType="TinyInt NOT NULL")]
		public byte rok
		{
			get
			{
				return this._rok;
			}
			set
			{
				if ((this._rok != value))
				{
					this.OnrokChanging(value);
					this.SendPropertyChanging();
					this._rok = value;
					this.SendPropertyChanged("rok");
					this.OnrokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identyfikator", DbType="Char(1) NOT NULL")]
		public char identyfikator
		{
			get
			{
				return this._identyfikator;
			}
			set
			{
				if ((this._identyfikator != value))
				{
					this.OnidentyfikatorChanging(value);
					this.SendPropertyChanging();
					this._identyfikator = value;
					this.SendPropertyChanged("identyfikator");
					this.OnidentyfikatorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nauczyciel")]
	public partial class nauczyciel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_nauczyciel;
		
		private string _imie;
		
		private string _nazwisko;
		
		private EntitySet<nauczyciel_przedmiot> _nauczyciel_przedmiots;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nauczycielChanging(System.Guid value);
    partial void Onid_nauczycielChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    #endregion
		
		public nauczyciel()
		{
			this._nauczyciel_przedmiots = new EntitySet<nauczyciel_przedmiot>(new Action<nauczyciel_przedmiot>(this.attach_nauczyciel_przedmiots), new Action<nauczyciel_przedmiot>(this.detach_nauczyciel_przedmiots));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nauczyciel", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_nauczyciel
		{
			get
			{
				return this._id_nauczyciel;
			}
			set
			{
				if ((this._id_nauczyciel != value))
				{
					this.Onid_nauczycielChanging(value);
					this.SendPropertyChanging();
					this._id_nauczyciel = value;
					this.SendPropertyChanged("id_nauczyciel");
					this.Onid_nauczycielChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nauczyciel_nauczyciel_przedmiot", Storage="_nauczyciel_przedmiots", ThisKey="id_nauczyciel", OtherKey="id_nauczyciel")]
		public EntitySet<nauczyciel_przedmiot> nauczyciel_przedmiots
		{
			get
			{
				return this._nauczyciel_przedmiots;
			}
			set
			{
				this._nauczyciel_przedmiots.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nauczyciel_przedmiots(nauczyciel_przedmiot entity)
		{
			this.SendPropertyChanging();
			entity.nauczyciel = this;
		}
		
		private void detach_nauczyciel_przedmiots(nauczyciel_przedmiot entity)
		{
			this.SendPropertyChanging();
			entity.nauczyciel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.przedmiot")]
	public partial class przedmiot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_przedmiot;
		
		private string _nazwa;
		
		private EntitySet<nauczyciel_przedmiot> _nauczyciel_przedmiots;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_przedmiotChanging(System.Guid value);
    partial void Onid_przedmiotChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    #endregion
		
		public przedmiot()
		{
			this._nauczyciel_przedmiots = new EntitySet<nauczyciel_przedmiot>(new Action<nauczyciel_przedmiot>(this.attach_nauczyciel_przedmiots), new Action<nauczyciel_przedmiot>(this.detach_nauczyciel_przedmiots));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_przedmiot", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_przedmiot
		{
			get
			{
				return this._id_przedmiot;
			}
			set
			{
				if ((this._id_przedmiot != value))
				{
					this.Onid_przedmiotChanging(value);
					this.SendPropertyChanging();
					this._id_przedmiot = value;
					this.SendPropertyChanged("id_przedmiot");
					this.Onid_przedmiotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="przedmiot_nauczyciel_przedmiot", Storage="_nauczyciel_przedmiots", ThisKey="id_przedmiot", OtherKey="id_przedmiot")]
		public EntitySet<nauczyciel_przedmiot> nauczyciel_przedmiots
		{
			get
			{
				return this._nauczyciel_przedmiots;
			}
			set
			{
				this._nauczyciel_przedmiots.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nauczyciel_przedmiots(nauczyciel_przedmiot entity)
		{
			this.SendPropertyChanging();
			entity.przedmiot = this;
		}
		
		private void detach_nauczyciel_przedmiots(nauczyciel_przedmiot entity)
		{
			this.SendPropertyChanging();
			entity.przedmiot = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sala")]
	public partial class sala : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_sala;
		
		private byte _pojemnosc;
		
		private short _numer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_salaChanging(System.Guid value);
    partial void Onid_salaChanged();
    partial void OnpojemnoscChanging(byte value);
    partial void OnpojemnoscChanged();
    partial void OnnumerChanging(short value);
    partial void OnnumerChanged();
    #endregion
		
		public sala()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sala", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_sala
		{
			get
			{
				return this._id_sala;
			}
			set
			{
				if ((this._id_sala != value))
				{
					this.Onid_salaChanging(value);
					this.SendPropertyChanging();
					this._id_sala = value;
					this.SendPropertyChanged("id_sala");
					this.Onid_salaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pojemnosc", DbType="TinyInt NOT NULL")]
		public byte pojemnosc
		{
			get
			{
				return this._pojemnosc;
			}
			set
			{
				if ((this._pojemnosc != value))
				{
					this.OnpojemnoscChanging(value);
					this.SendPropertyChanging();
					this._pojemnosc = value;
					this.SendPropertyChanged("pojemnosc");
					this.OnpojemnoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer", DbType="SmallInt NOT NULL")]
		public short numer
		{
			get
			{
				return this._numer;
			}
			set
			{
				if ((this._numer != value))
				{
					this.OnnumerChanging(value);
					this.SendPropertyChanging();
					this._numer = value;
					this.SendPropertyChanged("numer");
					this.OnnumerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nauczyciel_przedmiot")]
	public partial class nauczyciel_przedmiot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_nauczyciel_przedmiot;
		
		private System.Guid _id_nauczyciel;
		
		private System.Guid _id_przedmiot;
		
		private EntityRef<nauczyciel> _nauczyciel;
		
		private EntityRef<przedmiot> _przedmiot;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nauczyciel_przedmiotChanging(System.Guid value);
    partial void Onid_nauczyciel_przedmiotChanged();
    partial void Onid_nauczycielChanging(System.Guid value);
    partial void Onid_nauczycielChanged();
    partial void Onid_przedmiotChanging(System.Guid value);
    partial void Onid_przedmiotChanged();
    #endregion
		
		public nauczyciel_przedmiot()
		{
			this._nauczyciel = default(EntityRef<nauczyciel>);
			this._przedmiot = default(EntityRef<przedmiot>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nauczyciel_przedmiot", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_nauczyciel_przedmiot
		{
			get
			{
				return this._id_nauczyciel_przedmiot;
			}
			set
			{
				if ((this._id_nauczyciel_przedmiot != value))
				{
					this.Onid_nauczyciel_przedmiotChanging(value);
					this.SendPropertyChanging();
					this._id_nauczyciel_przedmiot = value;
					this.SendPropertyChanged("id_nauczyciel_przedmiot");
					this.Onid_nauczyciel_przedmiotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nauczyciel", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id_nauczyciel
		{
			get
			{
				return this._id_nauczyciel;
			}
			set
			{
				if ((this._id_nauczyciel != value))
				{
					if (this._nauczyciel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nauczycielChanging(value);
					this.SendPropertyChanging();
					this._id_nauczyciel = value;
					this.SendPropertyChanged("id_nauczyciel");
					this.Onid_nauczycielChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_przedmiot", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id_przedmiot
		{
			get
			{
				return this._id_przedmiot;
			}
			set
			{
				if ((this._id_przedmiot != value))
				{
					if (this._przedmiot.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_przedmiotChanging(value);
					this.SendPropertyChanging();
					this._id_przedmiot = value;
					this.SendPropertyChanged("id_przedmiot");
					this.Onid_przedmiotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nauczyciel_nauczyciel_przedmiot", Storage="_nauczyciel", ThisKey="id_nauczyciel", OtherKey="id_nauczyciel", IsForeignKey=true)]
		public nauczyciel nauczyciel
		{
			get
			{
				return this._nauczyciel.Entity;
			}
			set
			{
				nauczyciel previousValue = this._nauczyciel.Entity;
				if (((previousValue != value) 
							|| (this._nauczyciel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nauczyciel.Entity = null;
						previousValue.nauczyciel_przedmiots.Remove(this);
					}
					this._nauczyciel.Entity = value;
					if ((value != null))
					{
						value.nauczyciel_przedmiots.Add(this);
						this._id_nauczyciel = value.id_nauczyciel;
					}
					else
					{
						this._id_nauczyciel = default(System.Guid);
					}
					this.SendPropertyChanged("nauczyciel");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="przedmiot_nauczyciel_przedmiot", Storage="_przedmiot", ThisKey="id_przedmiot", OtherKey="id_przedmiot", IsForeignKey=true)]
		public przedmiot przedmiot
		{
			get
			{
				return this._przedmiot.Entity;
			}
			set
			{
				przedmiot previousValue = this._przedmiot.Entity;
				if (((previousValue != value) 
							|| (this._przedmiot.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._przedmiot.Entity = null;
						previousValue.nauczyciel_przedmiots.Remove(this);
					}
					this._przedmiot.Entity = value;
					if ((value != null))
					{
						value.nauczyciel_przedmiots.Add(this);
						this._id_przedmiot = value.id_przedmiot;
					}
					else
					{
						this._id_przedmiot = default(System.Guid);
					}
					this.SendPropertyChanged("przedmiot");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
