//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///
        ///&lt;!--deklaracja DOCTYPE --&gt;
        ///
        ///&lt;html&gt;					&lt;!--zdefiniowanie języka poprzez znacznik &lt;html&gt; --&gt;
        ///&lt;head&gt;					&lt;!--nagłówek, który dostarcza informacji o dokumencie--&gt;
        ///
        ///
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt; 
        ///
        ///&lt;!--Atrybut http-equiv służy do określania treści nagłówka odpowiedzi HTTP dla dokumentu HTML, tzn. serwer HTTP pobiera treść tego atrybutu i na jej podstawie tworzy odpowiedź HT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabela_klasy {
            get {
                return ResourceManager.GetString("tabela_klasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;!--deklaracja DOCTYPE --&gt;
        ///
        ///&lt;html&gt;					&lt;!--zdefiniowanie języka poprzez znacznik &lt;html&gt; --&gt;
        ///&lt;head&gt;					&lt;!--&quot;główka&quot;, która dostarcza informacji o dokumencie--&gt;
        ///
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///
        ///&lt;!--Atrybut http-equiv służy do określania treści nagłówka odpowiedzi HTTP dla dokumentu HTML, tzn. serwer HTTP pobiera treść tego atrybutu i na jej podstawie tworzy odpowiedź HTTP, c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabela_nauczyciel {
            get {
                return ResourceManager.GetString("tabela_nauczyciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;!--deklaracja DOCTYPE --&gt;
        ///
        ///&lt;html&gt;					&lt;!--zdefiniowanie języka poprzez znacznik &lt;html&gt; --&gt;
        ///&lt;head&gt;					&lt;!--&quot;główka&quot;, która dostarcza informacji o dokumencie--&gt;
        ///
        ///
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt; 
        ///
        ///&lt;!--Atrybut http-equiv służy do określania treści nagłówka odpowiedzi HTTP dla dokumentu HTML, tzn. serwer HTTP pobiera treść tego atrybutu i na jej podstawie tworzy odpowiedź HTTP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabela_sala {
            get {
                return ResourceManager.GetString("tabela_sala", resourceCulture);
            }
        }
    }
}
